### ISSUE TITLE
Can not configure proxy->router to set runtime dyamic baseurl

### ISSUE THREAD

**Issue by KahrLu** [refactorjs/http-proxy#9]
Hi @Teranode , I need 'router' to overwrite 'target' to set runtime dyamic baseurl in Nuxt3.rc-8.
Could you please archieve this function with http-proxy-middleware?
https://github.com/chimurai/http-proxy-middleware/blob/master/recipes/router.md
Thanks!

**Comment by Teranode** [comment]
are you asking for a feature like http-proxy-middleware, or are you asking for http-proxy-middleware to be usable with this module? Because its using http-proxy under its own hood...
